### ISSUE TITLE
Playlist linked

### ISSUE THREAD

**Issue by David-Baron** [thomasmds/PHPCrawler#6]
Bonjour Thomas,
Je viens de tester ton crawler
Un problème : il crawl les liens playlist de video et musique.
As tu un pathern pour ca?
Il faudrait suprimer les liens contenant "mpeg,png,jpeg..."

**Comment by David-Baron** [comment]
Ok j'ai trouver:
in crawler class at getTabLinks function
put what you want to omit like : 
if(strpos($value, "http://") !== false OR strpos($value, "https://") !== false OR strrpos($value, "mp3") !== false)

**Comment by David-Baron** [comment]
easier to previous line

**Comment by thomasmds** [comment]
Bonjour David,

Je ne crois pas que ce soit le bon endroit pour gérer ça.
Je n'ai pas vu de proposition en pull request ?

**Comment by Atome-TM** [comment]
J'ai rajouter à l'endroit où je filtre les fichiers, un tableau d'extensions à éviter.

Je te laisse faire un fork du projet, et proposer une liste plus complète si tu trouves ça nécessaire.
Merci pour tes messages.
